### ISSUE TITLE
[Bug] Cable can take out items from Quickshop's chest

### ISSUE THREAD

**Issue by Clexus** [xenondevs/Nova#107]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Nova 0.8.6 Spigot 1.18.1

### Expected behavior

It shouldn't be like that.

### Observed/Actual behavior

It seems you can't attach a cable directly but you can place a cable 2 blocks away and then directly to the chestshop.

### Steps to reproduce

Like above

### Errors

no

### Additional context

no

**Comment by ByteZ1337** [comment]
@Ghost-chu It won't work since we haven't implemented protection checks in our cable networks yet.

**Comment by NichtStudioCode** [comment]
> [qs-reremake-compat-nova-1.0-SNAPSHOT.zip](https://github.com/xenondevs/Nova/files/8097824/qs-reremake-compat-nova-1.0-SNAPSHOT.zip)
Disclaimer: I hadn't test it yet, just do a little really quick works.

Sadly, this does not work as these methods might be called asynchronously and ``ShopManager#getShopIncludeAttached`` accesses block states in order to find double chests, which can only be done from the main thread. Is there currently a way call this asynchronously?
