### ISSUE TITLE
[Bug] Dupe

### ISSUE THREAD

**Issue by NotZer0Two** [xenondevs/Nova#169]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Before creating a bug report, please validate that the issue you're encountering is not caused by another plugin (Remove all other plugins from the server). If it is, please name the plugin that causes the issue.

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova: 0.10.5, git-Purpur-1735 (MC: 1.19.1)

### Nova Addons and Versions

Machines 0.1.6, Logistics 0.1.2, Jetpacks 0.1.3

### Observed/Actual behavior

Duping the items inside the Gui's every gui have this problem

### Steps to reproduce

https://www.mediafire.com/file/vfbcvt33dvuacue/Java-runtime-gamma+2022.08.30+-+11.24.47.02.mp4/file

### Full server log

no errors

**Comment by NichtStudioCode** [comment]
Minecraft generally allows "duping items" if you're in creative mode. (If the client says "I have this item now" and the player is in creative, the server just allows that action). So this is probably a bug of your modded client (since you said touchscreen mode). Check if it works in survival mode.

**Comment by NotZer0Two** [comment]
bro its vanilla

**Comment by NotZer0Two** [comment]
just go on controls => mouse settings => Touch Screen mode ON

**Comment by NotZer0Two** [comment]
we found a fix with a custom plugin we made just make a check

**Comment by NichtStudioCode** [comment]
>just go on controls => mouse settings => Touch Screen mode ON

Nevermind then.

It's still some sort of desync issue. It's the same as if you press F on item to. It works in creative, because the client is allowed to do that. In survival, it just creates a ghost item that disappears after clicking on it.

>we found a fix with a custom plugin we made just make a check

Not sure how you would fix that with a plugin, as it is entirely client-side and the server gets no say in that. (You could prevent all creative inventory actions initiated by the player while looking at those guis, but it's not really an issue in creative anyways.)
