### ISSUE TITLE
[Request - Generic] mcpack file for geyser bedrock clients

### ISSUE THREAD

**Issue by Renkin42** [xenondevs/Nova#21]
**Describe your feature request.**
I currently run a server with cross-play compatibility using GeyserMC and Floodgate and was hoping to run this plugin on it, but unfortunately Bedrock clients are unable to receive the server resource pack. I have confirmed that I can convert a java resource pack to the bedrock format and send it to any bedrock client by placing it in the Geyser packs folder. However the converter I used only supports 1.16 and below, and the repository seems to have been deleted, so I doubt any 1.17 support will be forthcoming, so no luck converting it automatically. I did try editing mcpack.meta before running the conversion to trick it into treating it as a 1.16 file, but no dice, that just produces an empty resource pack. Not sure what would need to be changed within nova itself, presumably some change to detect if a bedrock client accepted the pack, or just a config option to bypass the check for compatibility? 

**Additional context**
The converter tool I used: https://rtm516.github.io/ConvertJavaTextureToBedrock/

**Comment by NichtStudioCode** [comment]
Nova is not compatible with any bedrock bridges. We're exploiting "features" to add blocks, items and GUIs which simply does not work this way on Bedrock.

**Comment by Renkin42** [comment]
I'm actually curious what doesn't work. My understanding of how new blocks are added is by using the nbt data of the blocks with the custom resource pack. Does bedrock just not allow modification of textures/models based on nbt? Or are there some deeper exploits of the java client beyond that that can't be utilized by bedrock? Sorry to be a pest, just very curious how this works.

**Comment by NichtStudioCode** [comment]
https://www.spigotmc.org/threads/520187/

**Comment by Renkin42** [comment]
Cool! Thanks for the read! Now I'm tempted to play with some of these mechanics myself and see if I can pull something off that works in both versions.

**Comment by Samplayz2007** [comment]
geysermc now supports Custom model data and stuff

**Comment by ByteZ1337** [comment]
I doubt bedrock supports the oversized characters we use for inventories though

**Comment by Samplayz2007** [comment]
there are mcpacks for sf with custom armors and item models

**Comment by Samplayz2007** [comment]
just saw ur reply...
um just try in ur free time ig

**Comment by Samplayz2007** [comment]
my server has a lot of bedrock players so it would be really cool if this works for them

**Comment by ByteZ1337** [comment]
> my server has a lot of bedrock players so it would be really cool if this works for them

We fully understand that Bedrock players are a large player base for a lot of Server. But it's pretty much a completely different game. Even if the bug we abuse to render GUIs would be a part of Bedrock as well, we still wouldn't be able to just use our texture there because of the different layout.

![image](https://user-images.githubusercontent.com/42820438/219958028-c263791b-6514-4927-9264-2274c3cbaa5a.png)

Bedrock natively supports custom GUIs, so to properly display Nova's inventories, we'd have to dynamically generate a mod for the Bedrock edition during runtime based on the installed addons (We both have absolutely 0 experience with the API).

Besides GUIs, we also use unused/replaceable blockstates from minecraft to avoid using ArmorStands when displaying blocks (Check out [our spigot thread](https://www.spigotmc.org/threads/advanced-resourcepack-mechanics-how-to-create-custom-items-blocks-guis-and-more.520187/)) for more information on that. I don't think Bedrock has the same system, so we'd need to resort back to ArmorStands which probably also have different rendering dimensions regarding x, y, z offset, etc.

And those are just 2 examples of the many problems we'd encounter when adding support. It's kind of like writing an entirely new Nova plugin just to support Bedrock players. Both of us don't have anywhere near enough spare time/motivation to code this entire system.

**Comment by Samplayz2007** [comment]
true... i guess its not worth it.. f bedrock JAVA SUPERMACY

**Comment by Hahaa13** [comment]
list geyser pack support:
 - custom model data item (https://wiki.geysermc.org/geyser/custom-items/)
 - custom font/gui (using font and JsonUi, have to do it by hand)
 - 3D item(No icon in inventory can make icon using 2D image)
 - armor/bow/crossbow/fishing rod (have to do it by hand)
List no support:
 - block(it is currently only 1 fork)(https://github.com/GeyserMC/Geyser/pull/3505)
