### ISSUE TITLE
[Request - Block] Mob Lamp

### ISSUE THREAD

**Issue by Sheikins** [xenondevs/Nova#33]
### Potential name of the block

Mob Lamp

### Describe the block

A lamp to prevent aggressive mob spawn within a radius of 32 blocks (configurable in the config). It will need electricity to operate. If a monster enters the radius it is automatically killed. (To be able to activate or deactivate this function in the config)

Like TorchMaster mods : https://gamewith.net/minecraft-guide/article/show/29210

![2021-09-29_14 55 21](https://user-images.githubusercontent.com/50546556/135274923-efdfa2e4-656c-4991-bfc8-4d98b4731950.png)

**Comment by EchocallingEarth** [comment]
Question: Would the height as well as the area covered be configurable.

By this, I mean that the area is say 16 block radius, height is set at 10. This could be very useful for things like mob grinders.
Also, I think the area should be based on the center, so the area light would kill within would be say 16 total, or 8 blocks in each direction. 

BTW - Note if circular then it would be less on the arcs of curves. This is because Minecraft is square. So I further suggest rather than radius using the square for the covered area.

Finally, I urge or recommend a lower setting than 32 as suggested only because of Minecraft's normal light levels.

**Comment by ByteZ1337** [comment]
> Also, I think the area should be based on the center, so the area light would kill within would be say 16 total, or 8 blocks in each direction. 

A mob lamp **prevents** hostile mobs from spawning. It doesn't kill them.

**Comment by EchocallingEarth** [comment]
> If a monster enters the radius it is automatically killed

I was basing the "KILL" part off the original post. Not off of how I suspected the system would work.

**Comment by ByteZ1337** [comment]
> I was basing the "KILL" part off the original post. Not off of how I suspected the system would work.

Then I see 0 ways how this could be used with mob farms.

**Comment by EchocallingEarth** [comment]
I think you clearly have missed the concept here

1st build a mob dropper (shorter than usual because hey we have this crazy new mob lamp thingy and maybe you have a limited amount of space to build upward)
2nd place said Mob Lamp at base of the dropper (NOTE the lamp would need to have a max allowed light height to do this - otherwise this I pointless hence my suggestion on restrictions)

Falling mob normally hits the ground and dies, now the mob dies at say 5 blocks above ground, and dropped items are collected. 

Now, do you understand...?

**Comment by ByteZ1337** [comment]
> I think you clearly have missed the concept here

No you just completely ignored my original comment. If we do implement the mob lamp it won't kill mobs that enter its range. We have a mob killer for that. It will just prevent hostile mobs from spawning in that range.

**Comment by NichtStudioCode** [comment]
Feature requests have been moved to [Discord](https://discord.gg/hnEknVWvUe).
