### ISSUE TITLE
[Request - Generic] Revisions to vanilla enchantment catogory

### ISSUE THREAD

**Issue by AllayBreeze** [xenondevs/Nova#335]
### Describe your feature request.

The current vanilla enchantment catogories have some incorrections:
1. Sharpness, Smite and Bane of Arthropods should also be applicable to axes. It's better to only remain these three to "weapon" catogory, and add a new "sword" catogory to contain Knockback, Fire Aspect, Looting and Sweeping Edge.
2. Thorns should be applicable to all kinds of armors, so it should be moved to "armor" catogory.
3. Efficiency should be applicable to shears, but on current Nova (0.16-alpha.3) it cannot. Since shears cannot have Silk Touch and Fortune, add a new catogorie to contain these two should be better.

**Comment by NichtStudioCode** [comment]
The vanilla enchantment categories just mirror the internal enchantment categories.

But you're correct, there was in inconsistency where some enchantments could not be applied with an anvil, because that actually calls `Enchantment#canEnchant`, which some enchantments override (such as efficiency, to allow shears). This has been fixed.
