### ISSUE TITLE
[Request - S3] S3 configuration is missing forcePathStyle

### ISSUE THREAD

**Issue by Whitebrim** [xenondevs/Nova#415]
### Describe your feature request.

Please add https://sdk.amazonaws.com/kotlin/api/latest/s3/aws.sdk.kotlin.services.s3/-s3-client/-config/-builder/force-path-style.html to config

### Additional context

```
  auto_upload:
    enabled: true
    service: amazon_s3
    endpoint: s3.brim.su
    region: us-east-1
    bucket: brimworld-api
    key_id: ***
    key_secret: ******
```

```
[20:42:20 ERROR]: [Nova] Failed to upload the resource pack!
software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.

Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: brimworld-api.s3.brim.su

Caused by: java.net.UnknownHostException: brimworld-api.s3.brim.su
```

**Comment by NichtStudioCode** [comment]
I'm not familiar with aws, but why should we use a legacy request style?

**Comment by tie** [comment]
For deployment of S3-compatible implementations (e.g. [minio](https://min.io), [garage](https://garagehq.deuxfleurs.fr), [seaweedfs](https://seaweedfs.com)) that do not use or support virtual-host-style requests (i.e. subdomains). For example, with path style requests, the request should be made to `s3.brim.su` instead of `brimworld-api.s3.brim.su` domain (with bucket in the URL path instead of being a subdomain). AWS SDKs supports this behavior with force_path_style option. See also https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

To be clear, this should be a boolean option in the service config since this behavior is legacy only for Amazon-hosted S3 service.

**Comment by Whitebrim** [comment]
> To be clear, this should be a boolean option in the service config

And `false` by default, I need it to be true, but Amazon S3 users won't change it.

**Comment by Whitebrim** [comment]
It's working now, thank you ❤️
