### ISSUE TITLE
Incorrect block picking behavior

### ISSUE THREAD

**Issue by Katalijst** [xenondevs/Nova#462]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.17-alpha.4 ; paper-1.21.1-81

### Nova Addons and Versions

My WIP addon

### Expected behavior

If you already have the block in your inventory it just move the selected item to an empty slot of the hotbar and then move your selected slot, or switch with the current selected slot item

### Observed/Actual behavior

The normal pick block behavior of minecraft is broken, if you already have the block in your inventory it duplicate to the current selected slot. There is also an induced visual glitch if you have an empty inventory and pick a custom block multiple time, once the hotbar is full and you pick it again you see the normal vanilla block

https://github.com/user-attachments/assets/5db3d46d-3203-49e1-bb0e-2c38045e7891

### Steps to reproduce

Pickup block in creative with empty inventory, custom or vanilla block

### Server log

[latest.log](https://github.com/user-attachments/files/17010176/latest.log)

**Comment by NichtStudioCode** [comment]
The ghost item issue has been addressed in ef7f4002ecc08d9b88af510666853cafd2e001b4.

I don't think that the other issues related to creative block picking can be (easily) fixed. This is because in creative mode, there is only `ServerboundSetCreativeModeSlotPacket`, so Nova has to guess what constitutes a block pick by comparing the currently targeted block to the item that the client wants to add to their inventory. (This already has false positives when you interact with items in your inventory that have the same type as the item of the backing block state you're looking at.)
The main problem that prevents the "more advanced" block picking functionality from being replicated as well is that, in case of a full hotbar, the client moves the previous item stack to a different place in the inventory, but the packet for that is only sent after the player opens their inventory, which would make this quite difficult to track.
While it might be possible to hack something together here, I don't think it's worth the effort, considering the most important functionality (clone the block you're looking at) works fine.
