### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xdomciakx** [xenondevs/Nova#61]
### Agreements

- [X] I am running the latest version of Nova.
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Other plugins

This issue is about a specific plugin incompatibility.

### Plugin Version, Server Software, Server Version

Paper version git-Paper-243 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 20903fc)

### Expected behavior

So simply my server is running nova and sometimes nova starts generating exceptions what causes server ticks behind and it lags whole server until I restart..

### Observed/Actual behavior

I just saw over spammed console and ticks behind on server while that happend.

### Steps to reproduce

Just simply run the server

**Comment by NichtStudioCode** [comment]
- You didn't give this issue a title
- Your server is severely outdated.
- You selected "This issue is about a specific plugin incompatibility", yet you don't actually know that and also don't give a name for a plugin.
- Expected behavior is for what you expect, not what you've observed.
- You didn't add the exceptions you mentioned on Discord

Please open a new issue once you have updated to the latest Paper version and checked if this problem also occurs without any other plugins on the server (as required to make a bug report).
