### ISSUE TITLE
[Bug] Nova causes Energetic Storage crafting recipes to not work.

### ISSUE THREAD

**Issue by SeanOMik** [xenondevs/Nova#7]
**Describe the bug**
Nova causes Energetic Storage crafting recipes to not work.

**To Reproduce**
1. Install [Energetic Storage](https://github.com/SeanOMik/EnergeticStorage)
2. Install Nova
3. [Attempt to craft an ES System](https://github.com/SeanOMik/EnergeticStorage/wiki/Creating-an-ES-System)
4. Won't be able to craft it.

**Expected behavior**
For the ES System to be able to be crafted.

**Errors**
There are no errors in the console, it appears to register the recipes fine.

**Screenshots**
[Attempt to craft](https://user-images.githubusercontent.com/84059085/124421281-204c3a00-dd2f-11eb-94a2-c367dc5aa09d.png)

**Additional context**
I'm the developer of Energetic Storage so I'm willing to work with you guys to try to find the issue. I think it might help if I show you how I register my recipes (using Spigot API), [here's the source](https://github.com/SeanOMik/EnergeticStorage/blob/master/src/main/java/net/seanomik/energeticstorage/utils/ItemRecipies.java).

**Comment by NichtStudioCode** [comment]
Thanks for reporting!
The issue was caused by the AdvancementAPI reloading everything and thereby deleting previously registered recipes.
The fix will be included in the next version, if you need to work around this now you should be able to add Nova as "softdepend" in the plugin.yml. This will cause your plugin to be loaded after Nova and your recipes won't get removed.

**Comment by SeanOMik** [comment]
Awesome, I'll notify the person that originally made the issue on my Github that it will be fixed in the next release of Nova. It's not super important right now, but glad to hear its fixed!
